### ISSUE TITLE
Parse Newick

### ISSUE THREAD

**Issue by aesse** [bodenlab/GRASP#3]
Encountered issue with user trying to pass in a Newick string with labels that contained brackets '()' 

bnkit can't properly parse the Newick string if node labels include brackets 

Possibly add catch around PhyloTree.loadNewick() in loadData() to highlight the naming requirements?

**Comment by mikaelboden** [comment]
This sounds like (a) an inherent problem with the Newick format and (b) something that cannot be caught. The problem must be with programs that allow the user to type in such names.
/Mikael

On 5 Jan 2016, at 2:32 PM, aesse <notifications@github.com<mailto:notifications@github.com>> wrote:


Encountered issue with user trying to pass in a Newick string with labels that contained brackets '()'

bnkit can't properly parse the Newick string if node labels include brackets

Possibly add catch around PhyloTree.loadNewick() in loadData() to highlight the naming requirements?

—
Reply to this email directly or view it on GitHub<https://github.com/bodenlab/ASR/issues/3>.

Mikael Bodén  |  Group Leader Bioinformatics  |  Associate Professor
School of Chemistry and Molecular Biosciences (Faculty of Science)
The University of Queensland | Brisbane QLD 4072 Australia
ph  (07) 3365 1307  |  e  m.boden@uq.edu.au<mailto:m.boden@uq.edu.au>  | w www.scmb.uq.edu.au/staff/mikael-boden<http://www.scmb.uq.edu.au/staff/mikael-boden>
