### ISSUE TITLE
meaning of the numbers associated to internal node names

### ISSUE THREAD

**Issue by eranbio** [bodenlab/GRASP#69]
Hello,
I am using the command line version and see that there is a float number associated with underscore to the internal node names, e.g.:  N1_0.390.  Can briefly explain the meaning of this number?
Thanks,
Eran

**Comment by mikaelboden** [comment]
Hi Eran,
GRASP a does not add this number; it puts the prefix N<ancestor> there however, followed by underscore and a label supplied by the Newick input file. I strongly suspect that the Newick file was generated by a program that annotates each branch point with bootstrap stats. FastTree does this by default (and you can turn it off with -nosupport I think). You can of course edit the file manually to remove those internal numbers; be careful not to remove distances though.

Mikael
On 20 Jun 2020, at 2:02 am, eranbio <notifications@github.com> wrote:

﻿

Hello,
I am using the command line version and see that there is a float number associated with underscore to the internal node names, e.g.: N1_0.390. Can briefly explain the meaning of this number?
Thanks,
Eran

**Comment by eranbio** [comment]
Thanks Mikael! Indeed I was using FastTree. So it is all clear now.
